# Generated by Django 5.2.8 on 2025-11-13 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0005_job_seeker_delete_seeker'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_name', to='jobapp.recruiter'),
            preserve_default=False,
        ),
    ]
