# Generated by Django 5.2.8 on 2025-11-13 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0006_jobpost_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.TextField(blank=True)),
                ('projects', models.TextField(blank=True)),
                ('experience', models.TextField(blank=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('tenth_school', models.CharField(blank=True, max_length=150)),
                ('tenth_board', models.CharField(blank=True, max_length=100)),
                ('tenth_year', models.CharField(blank=True, max_length=10)),
                ('tenth_percentage', models.CharField(blank=True, max_length=10)),
                ('twelfth_school', models.CharField(blank=True, max_length=150)),
                ('twelfth_board', models.CharField(blank=True, max_length=100)),
                ('twelfth_year', models.CharField(blank=True, max_length=10)),
                ('twelfth_percentage', models.CharField(blank=True, max_length=10)),
                ('bachelors_specialization', models.CharField(blank=True, max_length=150)),
                ('bachelors_institute', models.CharField(blank=True, max_length=100)),
                ('bachelors_year', models.CharField(blank=True, max_length=10)),
                ('bachelors_cgpa', models.CharField(blank=True, max_length=10)),
                ('masters_specialization', models.CharField(blank=True, max_length=150)),
                ('masters_institute', models.CharField(blank=True, max_length=100)),
                ('masters_year', models.CharField(blank=True, max_length=10)),
                ('masters_cgpa', models.CharField(blank=True, max_length=10)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('portfolio', models.URLField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='jobapp.job_seeker')),
            ],
        ),
    ]
